POST http://localhost:4000/users/add
Content-Type: application/json
  
{
    "name" : "Albin Matson Gyllang3",
    "username" : "ALBA",
    "email" : "ALBA@ALBA.se",
    "password":"ALBA"
        
}
###

GET http://localhost:4000/users/616d79d21b93acbe8ec54c50
Content-Type: application/json

