# POST http://localhost:4000/drinks/update/6159cfd58f99645030aa98e5
# Content-Type: application/json
  
# {
#     "name" : "Just Vodka 3.0",
#     "description" : "Pour to mouth",
#     "ingredients" : ["Vodka"]
# }