POST http://localhost:4000/users/add
Content-Type: application/json
  
{
    "name" : "Albin Matson Gyllang3",
    "username" : "newnew",
    "email" : "ALBA222@ALBA.se",
    "password":"ALBA"
        
}
###
GET http://localhost:4000/users/61703ee59c6e5c93a2caad5f
Content-Type: application/json

