POST http://localhost:4000/users/add
Content-Type: application/json
  
{
    "name" : "Albin Matson Gyllang3",
    "username" : "albin",
    "email" : "albin@albin.se",
    "password":"albin"
        
}
###
GET http://localhost:4000/users/61711297f6c09f2cc42cade6
Content-Type: application/json

