
###// Create a comment - /comments/create - have to send object with this structure, 
    ##& "drinkId" - which drink is being commented
    ##& "userId" - which user commented
    ##& "comment" - what the user commented

    ##& {
    ##&     "drinkId" : "6159cfd58f99645030aa98e5",
    ##&     "userId" : "6159cc4bfe289ebe9ac43247",
    ##&     "comment" : "tycker den är ganska god om jag ska vara helt ärlig1"
    ##& }

POST http://localhost:4000/comments/create
Content-Type: application/json 
  
{
    "cocktailDBId" : "15997",
    "drinkId" : "6159cfd58f99645030aa98e5",
    "userId" : "61704cf61df5011f8bd1469c",
    "comment" : "Taste great!"
}


###// find all comments for a drink - /comments/${drinkId}
GET http://localhost:4000/comments/15997
Content-Type: application/json
  
###//Delete a comment - /comments/delete/${commentId}
# DELETE  http://localhost:4000/comments/delete/6159ee01d7d30bfa207af17e
# Content-Type: application/json
DELETE http://localhost:4000/comments/delete/61702cab9e1389273687b16e
Content-Type: application/json
