# POST http://localhost:4000/drinks/update/6159cfd58f99645030aa98e5
# Content-Type: application/json
  
# {
#     "name" : "Just Vodka 3.0",
#     "description" : "Pour to mouth",
#     "ingredients" : ["Vodka"]
# }

# POST http://localhost:4000/drinks/create
# Content-Type: application/json
  
# {   "userId" : "616d5fe83b0b7f7495ecae87",
#     "name" : "Just Vodka 3.0",
#     "description" : "Pour to mouth",
#     "ingredients" : ["Vodka"]
# }

## GET ALL COMMENTS from a drink 
GET http://localhost:4000/comments/616d622a3b0b7f7495ecae8e
Content-Type: application/json
  
